### ISSUE TITLE
Date and time of match data?

### ISSUE THREAD

**Issue by mensch72** [obrienjoey/snooker_rankings#1]
Dear Joey, I'm a network scientist and snooker fan, and am delighted that the Wizard of Wishaw is no. 1! I'd like to play around with the data and wondered whether you also have date and time of all matches?

**Comment by obrienjoey** [comment]
Unfortunately I don't have the exact dates at which the matches were played, the only temporal level I have for the games is at the season level which has been included. Happy to help with any additional queries.
